server:
   port: 8083
   servlet:
      context-path: /api/students

spring:
   application:
      name: student-service
   datasource:
      url: jdbc:h2:mem:schooldb
      driver-class-name: org.h2.Driver
      username: sa
      password:
   h2:
      console:
         enabled: true
         path: /h2-console

   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true
   jackson:
      serialization:
         fail-on-empty-beans: false

eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
   instance:
      prefer-ip-address: true

jwt:
   secret: my-secret-jwt-key # Same as used in auth-service

logging:
   level:
      org.springframework.security: DEBUG
      com.schoolmanagement.studentservice: DEBUG

management:
   endpoints:
      web:
         exposure:
            include: "*"
